### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by odonckers** [camgrigo/service#1]
This app looks amazing, but could not build it because it is not built in the latest Swift.  Could you please update it, that would be really helpful! ;)

**Comment by camgrigo** [comment]
I fixed the Realm and Xcode 8 problem, but the model needs some work. You can find a playground with the prototype by opening the project.

**Comment by odonckers** [comment]
This is a little overdue, but I am running Xcode 7, not 8. So that's the reason that it would not work for me. I'm going to install Xcode 8 and try again, and maybe it will work this time.
